namespace Stationary.Ftms.Dashboard.Core;

public readonly record struct TelemetrySnapshot(
    DateTimeOffset CapturedAt,
    FtmsMachineDataType MachineType,
    double? SpeedKilometersPerHour,
    double? CadenceRpm,
    short? PowerWatts,
    short? ResistanceTenths,
    byte? HeartRateBeatsPerMinute,
    uint? TotalDistanceMeters,
    double? AverageSpeedKilometersPerHour = null,
    double? AverageCadenceRpm = null,
    short? AveragePowerWatts = null,
    short? InclinationTenths = null,
    short? RampAngleTenths = null,
    ushort? PositiveElevationGainMeters = null,
    ushort? NegativeElevationGainMeters = null,
    ushort? InstantaneousPaceSecondsPerKilometre = null,
    ushort? AveragePaceSecondsPerKilometre = null,
    ushort? StepCount = null,
    ushort? StrideCount = null,
    ushort? StrokeCount = null,
    byte? MetabolicEquivalentTenths = null,
    ushort? TotalEnergyKilocalories = null,
    ushort? EnergyPerHourKilocalories = null,
    byte? EnergyPerMinuteKilocalories = null,
    ushort? ElapsedTimeSeconds = null,
    ushort? RemainingTimeSeconds = null,
    short? ForceOnBeltNewtons = null,
    ushort? Floors = null,
    bool? IsMovingBackward = null,
    TelemetryField ReportedFields = TelemetryField.None);