namespace Stationary.Ftms.Dashboard.Core;

internal static class TrainingWorkoutLibrary
{
    private const string EaseInName = "Ease in";
    private const string EasyEnduranceName = "Easy endurance";
    private const string EasyFloatName = "Easy float";
    private const string SpinDownName = "Spin down";
    private const string QuickFeetName = "Quick feet";
    private const string WarmUpName = "Warm up";
    private const string CoolDownName = "Cool down";
    private const string FloatName = "Float";
    private const string EnduranceName = "Endurance";
    private const string TempoCloseName = "Tempo close";
    private const string SweetSpotName = "Sweet spot";
    private const string TempoSurgeName = "Tempo surge";
    private const string UnderName = "Under";
    private const string OverName = "Over";
    private const string Vo2Name = "VO2";
    private const string Vo2EffortName = "VO2 effort";
    private const string SetRecoveryName = "Set recovery";
    private const string EasyRollName = "Easy roll";
    private const string SpinUpName = "Spin-up";
    private const string TorqueName = "Torque";
    private const string CadenceCloseName = "Cadence close";
    private const string BurstName = "Burst";
    private const string StartWithLightSpin = "Start with a light spin.";
    private const string FinishFresher = "Finish fresher than you started.";
    private const string BuildSmoothly = "Build smoothly.";
    private const string LightenGear = "Lighten the gear.";
    private const string LetBreathingSettle = "Let your breathing settle.";
    private const string FinishControlled = "Finish controlled.";
    private const string EaseOffGradually = "Ease off gradually.";
    private const string FinishWithReserve = "Finish with reserve.";
    private const string RecoverBeforeRepeating = "Recover fully before repeating.";
    private const string RecoverBeforeSecondSet = "Recover fully before the second set.";
    private const string SettleBelowThreshold = "Settle below threshold.";
    private const string LiftPowerWithoutRushingCadence = "Lift power without rushing cadence.";
    private const string ReturnToSteadyControl = "Return to steady control.";
    private const string PushFirmly = "Push firmly, stay smooth.";
    private const string KeepPedalingLightly = "Keep pedaling lightly.";
    private const string RepeatSamePressure = "Repeat the same pressure.";
    private const string FinishFirstSetControlled = "Finish the first set controlled.";
    private const string KeepPedalsMoving = "Keep the pedals moving.";
    private const string ReturnToRelaxedRhythm = "Return to a relaxed rhythm.";
    private const string PressSmoothly = "Press smoothly through the full stroke.";
    private const string ShiftLighterAndSpinFreely = "Shift lighter and spin freely.";
    private const string RepeatSameAcceleration = "Repeat the same acceleration.";
    private const string AccelerateSharply = "Accelerate sharply.";
    private const string KeepMovingNoCoast = "Keep moving, do not coast.";
    private const string RecoverCompletelyBeforeSecondSet = "Recover completely before the second set.";
    private const string FinishSharp = "Finish sharp, not all-out.";

    public static IReadOnlyList<TrainingWorkout> Create() =>
    [
        Recovery(TrainingExperienceLevel.Beginner),
        Recovery(TrainingExperienceLevel.Developing),
        Recovery(TrainingExperienceLevel.Intermediate),
        Recovery(TrainingExperienceLevel.Experienced),
        Recovery(TrainingExperienceLevel.Advanced),
        Endurance(TrainingExperienceLevel.Beginner),
        Endurance(TrainingExperienceLevel.Developing),
        Endurance(TrainingExperienceLevel.Intermediate),
        Endurance(TrainingExperienceLevel.Experienced),
        Endurance(TrainingExperienceLevel.Advanced),
        TempoSweetSpot(TrainingExperienceLevel.Beginner),
        TempoSweetSpot(TrainingExperienceLevel.Developing),
        TempoSweetSpot(TrainingExperienceLevel.Intermediate),
        TempoSweetSpot(TrainingExperienceLevel.Experienced),
        TempoSweetSpot(TrainingExperienceLevel.Advanced),
        Threshold(TrainingExperienceLevel.Beginner),
        Threshold(TrainingExperienceLevel.Developing),
        Threshold(TrainingExperienceLevel.Intermediate),
        Threshold(TrainingExperienceLevel.Experienced),
        Threshold(TrainingExperienceLevel.Advanced),
        Vo2Max(TrainingExperienceLevel.Beginner),
        Vo2Max(TrainingExperienceLevel.Developing),
        Vo2Max(TrainingExperienceLevel.Intermediate),
        Vo2Max(TrainingExperienceLevel.Experienced),
        Vo2Max(TrainingExperienceLevel.Advanced),
        CadenceSkills(TrainingExperienceLevel.Beginner),
        CadenceSkills(TrainingExperienceLevel.Developing),
        CadenceSkills(TrainingExperienceLevel.Intermediate),
        CadenceSkills(TrainingExperienceLevel.Experienced),
        CadenceSkills(TrainingExperienceLevel.Advanced),
        Anaerobic(TrainingExperienceLevel.Beginner),
        Anaerobic(TrainingExperienceLevel.Developing),
        Anaerobic(TrainingExperienceLevel.Intermediate),
        Anaerobic(TrainingExperienceLevel.Experienced),
        Anaerobic(TrainingExperienceLevel.Advanced),
    ];

    private static TrainingWorkout Recovery(TrainingExperienceLevel level) => level switch
    {
        TrainingExperienceLevel.Beginner => Workout("recovery-beginner", "Reset and Roll", "Short aerobic recovery with gentle cadence changes.", TrainingObjective.Recovery, level,
            M(EaseInName, 5, 45, StartWithLightSpin, false),
            M("Smooth roll", 6, 50, "Relax your shoulders and pedal circles.", true, 85, 95),
            M(EasyFloatName, 2, 42, "Let the effort fall away.", false),
            M("Smooth roll", 6, 52, "Keep the pedals light.", true, 85, 95),
            M(SpinDownName, 4, 45, FinishFresher, false)),
        TrainingExperienceLevel.Developing => Workout("recovery-developing", "Reset Flow", "Controlled recovery volume with light spin-ups.", TrainingObjective.Recovery, level,
            M(EaseInName, 5, 45, StartWithLightSpin, false),
            M(EasyEnduranceName, 8, 52, "Stay conversational.", true, 85, 95),
            S("Spin-up", 30, 58, "Increase cadence without pushing the gear.", true, 100, 110),
            M(EasyFloatName, 2, 42, "Return to an effortless rhythm.", false),
            M(EasyEnduranceName, 8, 54, "Keep breathing calm.", true, 85, 95),
            M(SpinDownName, 5, 45, FinishFresher, false)),
        TrainingExperienceLevel.Intermediate => Workout("recovery-intermediate", "Calm Cadence", "Easy aerobic work with a small neuromuscular refresh.", TrainingObjective.Recovery, level,
            M(EaseInName, 6, 45, StartWithLightSpin, false),
            M(EasyEnduranceName, 8, 54, "Relax through the full pedal stroke.", true, 85, 95),
            S(QuickFeetName, 45, 62, "Spin fast, not hard.", true, 100, 110),
            M(EasyFloatName, 2, 45, "Let your heart rate settle.", false),
            M(EasyEnduranceName, 10, 55, "Keep the pressure deliberately low.", true, 85, 95),
            S(QuickFeetName, 45, 62, "Stay smooth at high cadence.", true, 100, 110),
            M(SpinDownName, 5, 45, FinishFresher, false)),
        TrainingExperienceLevel.Experienced => Workout("recovery-experienced", "Restoration Ride", "Longer recovery ride that preserves pedaling economy.", TrainingObjective.Recovery, level,
            M(EaseInName, 6, 45, StartWithLightSpin, false),
            M(EasyEnduranceName, 10, 55, "Stay conversational.", true, 85, 95),
            S(QuickFeetName, 60, 64, "Spin up with no tension.", true, 100, 112),
            M(EasyFloatName, 3, 45, "Let the effort fall away.", false),
            M(EasyEnduranceName, 12, 56, "Keep the gear light.", true, 85, 95),
            S(QuickFeetName, 60, 64, "Move the legs without forcing power.", true, 100, 112),
            M(SpinDownName, 6, 45, FinishFresher, false)),
        TrainingExperienceLevel.Advanced => Workout("recovery-advanced", "Long Reset", "Low-stress recovery volume with controlled cadence work.", TrainingObjective.Recovery, level,
            M(EaseInName, 8, 45, StartWithLightSpin, false),
            M(EasyEnduranceName, 12, 56, "Keep the effort light and rhythmic.", true, 85, 95),
            S(QuickFeetName, 60, 65, "Spin up with no tension.", true, 102, 114),
            M(EasyFloatName, 3, 45, "Let the effort fall away.", false),
            M(EasyEnduranceName, 15, 58, "Stay conversational.", true, 85, 95),
            S(QuickFeetName, 60, 65, "Move the legs without forcing power.", true, 102, 114),
            M(SpinDownName, 7, 45, FinishFresher, false)),
        _ => throw new ArgumentOutOfRangeException(nameof(level)),
    };

    private static TrainingWorkout Endurance(TrainingExperienceLevel level) => level switch
    {
        TrainingExperienceLevel.Beginner => Workout("endurance-beginner", "Aerobic Ladder", "Progressive aerobic intervals with relaxed recoveries.", TrainingObjective.Endurance, level,
            M(WarmUpName, 6, 50, BuildSmoothly, false),
            M(Numbered(EnduranceName, 1), 6, 62, "Settle into an easy rhythm.", true, 85, 95),
            M(FloatName, 2, 50, LightenGear, false),
            M(Numbered(EnduranceName, 2), 8, 65, "Breathe steadily.", true, 85, 95),
            M(FloatName, 2, 50, LightenGear, false),
            M(Numbered(EnduranceName, 3), 6, 68, FinishControlled, true, 85, 95),
            M(CoolDownName, 5, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Developing => Workout("endurance-developing", "Aerobic Cruise", "Three aerobic blocks with small cadence variations.", TrainingObjective.Endurance, level,
            M(WarmUpName, 7, 50, BuildSmoothly, false),
            M(Numbered(EnduranceName, 1), 8, 65, "Stay relaxed at a natural cadence.", true, 85, 95),
            M(FloatName, 2, 52, LetBreathingSettle, false),
            M(Numbered(EnduranceName, 2), 10, 68, "Keep pressure smooth.", true, 85, 95),
            M(FloatName, 2, 52, LightenGear, false),
            M(Numbered(EnduranceName, 3), 8, 70, "Finish with quiet shoulders.", true, 88, 98),
            M(CoolDownName, 6, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Intermediate => Workout("endurance-intermediate", "Endurance Steps", "Aerobic durability with a controlled tempo finish.", TrainingObjective.Endurance, level,
            M(WarmUpName, 8, 50, BuildSmoothly, false),
            M(Numbered(EnduranceName, 1), 10, 68, "Stay patient and economical.", true, 85, 95),
            M(FloatName, 2, 52, "Let the effort reset.", false),
            M(Numbered(EnduranceName, 2), 12, 72, "Hold a firm but sustainable rhythm.", true, 85, 95),
            M(TempoCloseName, 5, 78, "Lift pressure without straining.", true, 88, 98),
            M(FloatName, 3, 52, "Return to easy pedaling.", false),
            M(Numbered(EnduranceName, 3), 8, 70, "Finish smoothly.", true, 85, 95),
            M(CoolDownName, 7, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Experienced => Workout("endurance-experienced", "Durability Blocks", "Long aerobic blocks with a disciplined negative split.", TrainingObjective.Endurance, level,
            M(WarmUpName, 10, 50, BuildSmoothly, false),
            M(Numbered(EnduranceName, 1), 15, 70, "Remain patient and aerodynamic.", true, 85, 95),
            M(FloatName, 3, 52, LightenGear, false),
            M(Numbered(EnduranceName, 2), 15, 74, "Keep the pressure even.", true, 85, 95),
            M(TempoCloseName, 6, 82, "Build only in the final minutes.", true, 88, 98),
            M(FloatName, 3, 52, "Let the effort reset.", false),
            M(Numbered(EnduranceName, 3), 10, 72, FinishControlled, true, 85, 95),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Advanced => Workout("endurance-advanced", "Aerobic Progression", "Extended endurance work that finishes just below tempo.", TrainingObjective.Endurance, level,
            M(WarmUpName, 12, 50, BuildSmoothly, false),
            M(Numbered(EnduranceName, 1), 18, 70, "Stay patient and economical.", true, 85, 95),
            M(FloatName, 3, 52, LightenGear, false),
            M(Numbered(EnduranceName, 2), 20, 75, "Hold a firm aerobic rhythm.", true, 85, 95),
            M(TempoCloseName, 8, 84, "Progress only if form remains quiet.", true, 88, 98),
            M(FloatName, 3, 52, "Let the effort reset.", false),
            M(Numbered(EnduranceName, 3), 12, 73, FinishControlled, true, 85, 95),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        _ => throw new ArgumentOutOfRangeException(nameof(level)),
    };

    private static TrainingWorkout TempoSweetSpot(TrainingExperienceLevel level) => level switch
    {
        TrainingExperienceLevel.Beginner => Workout("tempo-beginner", "Sweet Spot Steps", "Introductory tempo intervals with full recovery.", TrainingObjective.TempoSweetSpot, level,
            M(WarmUpName, 8, 52, BuildSmoothly, false),
            M("Tempo 1", 6, 82, "Controlled pressure, no strain.", true, 82, 92),
            M(FloatName, 3, 52, "Recover fully before the next block.", false),
            M("Tempo 2", 6, 85, "Stay tall and relaxed.", true, 82, 92),
            M(FloatName, 3, 52, LetBreathingSettle, false),
            M("Tempo 3", 5, 88, "Finish controlled.", true, 82, 92),
            M(CoolDownName, 6, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Developing => Workout("tempo-developing", "Sweet Spot Build", "Three progressive sweet spot blocks.", TrainingObjective.TempoSweetSpot, level,
            M(WarmUpName, 9, 52, BuildSmoothly, false),
            M(Numbered(SweetSpotName, 1), 8, 86, "Find a sustainable rhythm.", true, 82, 92),
            M(FloatName, 3, 52, "Recover fully before the next block.", false),
            M(Numbered(SweetSpotName, 2), 8, 89, "Keep pressure smooth.", true, 82, 92),
            M(FloatName, 3, 52, LetBreathingSettle, false),
            M(Numbered(SweetSpotName, 3), 7, 92, FinishWithReserve, true, 82, 92),
            M(CoolDownName, 7, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Intermediate => Workout("tempo-intermediate", "Sweet Spot Overlaps", "Sweet spot blocks with short controlled surges.", TrainingObjective.TempoSweetSpot, level,
            M(WarmUpName, 10, 52, BuildSmoothly, false),
            M(Numbered(SweetSpotName, 1), 8, 88, "Settle into firm pressure.", true, 82, 92),
            M(TempoSurgeName, 2, 95, "Lift the gear without sprinting.", true, 84, 94),
            M(FloatName, 4, 52, "Recover fully before the next set.", false),
            M(Numbered(SweetSpotName, 2), 10, 90, "Keep the effort controlled.", true, 82, 92),
            M(TempoSurgeName, 2, 97, "Lift the gear without sprinting.", true, 84, 94),
            M(FloatName, 4, 52, LetBreathingSettle, false),
            M(Numbered(SweetSpotName, 3), 8, 92, FinishWithReserve, true, 82, 92),
            M(CoolDownName, 7, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Experienced => Workout("tempo-experienced", "Sweet Spot Waves", "Long sweet spot sets that rehearse changing pressure.", TrainingObjective.TempoSweetSpot, level,
            M(WarmUpName, 12, 52, BuildSmoothly, false),
            M(Numbered(SweetSpotName, 1), 10, 90, "Find a sustainable rhythm.", true, 82, 92),
            M(TempoSurgeName, 3, 98, "Lift pressure, keep cadence calm.", true, 84, 94),
            M(Numbered(SweetSpotName, 2), 7, 90, "Return to controlled pressure.", true, 82, 92),
            M(FloatName, 4, 52, "Recover fully before the next set.", false),
            M(Numbered(SweetSpotName, 3), 10, 92, "Stay focused and quiet.", true, 82, 92),
            M(TempoSurgeName, 3, 100, "Lift pressure, keep cadence calm.", true, 84, 94),
            M(Numbered(SweetSpotName, 4), 7, 92, FinishWithReserve, true, 82, 92),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Advanced => Workout("tempo-advanced", "Sweet Spot Cascade", "Extended sweet spot work with controlled over-unders.", TrainingObjective.TempoSweetSpot, level,
            M(WarmUpName, 12, 52, BuildSmoothly, false),
            M(Numbered(SweetSpotName, 1), 12, 92, "Find a sustainable rhythm.", true, 82, 92),
            M(TempoSurgeName, 3, 100, "Lift pressure without chasing cadence.", true, 84, 94),
            M(Numbered(SweetSpotName, 2), 8, 92, "Return to controlled pressure.", true, 82, 92),
            M(FloatName, 4, 52, "Recover fully before the next set.", false),
            M(Numbered(SweetSpotName, 3), 12, 94, "Stay focused and quiet.", true, 82, 92),
            M(TempoSurgeName, 3, 102, "Lift pressure without chasing cadence.", true, 84, 94),
            M(Numbered(SweetSpotName, 4), 8, 94, FinishWithReserve, true, 82, 92),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        _ => throw new ArgumentOutOfRangeException(nameof(level)),
    };

    private static TrainingWorkout Threshold(TrainingExperienceLevel level) => level switch
    {
        TrainingExperienceLevel.Beginner => Workout("threshold-beginner", "Threshold Primer", "Short threshold work with generous recovery.", TrainingObjective.Threshold, level,
            M(WarmUpName, 10, 55, BuildSmoothly, false),
            M("Threshold 1", 5, 95, "Hold a strong, controlled rhythm.", true, 80, 90),
            M(FloatName, 4, 52, RecoverBeforeRepeating, false),
            M("Threshold 2", 5, 98, "Hold form, not tension.", true, 80, 90),
            M(FloatName, 4, 52, RecoverBeforeRepeating, false),
            M("Threshold 3", 4, 100, FinishControlled, true, 80, 90),
            M(CoolDownName, 7, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Developing => Workout("threshold-developing", "Threshold Sets", "Classic threshold sets with controlled recoveries.", TrainingObjective.Threshold, level,
            M(WarmUpName, 10, 55, BuildSmoothly, false),
            M("Threshold 1", 7, 98, "Settle into a repeatable effort.", true, 80, 90),
            M(FloatName, 4, 52, RecoverBeforeRepeating, false),
            M("Threshold 2", 7, 100, "Keep power stable.", true, 80, 90),
            M(FloatName, 4, 52, RecoverBeforeRepeating, false),
            M("Threshold 3", 6, 102, FinishControlled, true, 80, 90),
            M(CoolDownName, 7, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Intermediate => Workout("threshold-intermediate", "Threshold Over-Unders", "Threshold work that practices clearing short surges.", TrainingObjective.Threshold, level,
            M(WarmUpName, 12, 55, BuildSmoothly, false),
            M(Numbered(UnderName, 1), 4, 94, "Settle just below threshold.", true, 80, 90),
            M(Numbered(OverName, 1), 2, 104, "Lift power, then regain control.", true, 82, 92),
            M(Numbered(UnderName, 2), 4, 96, "Keep breathing deliberate.", true, 80, 90),
            M(FloatName, 5, 52, RecoverBeforeSecondSet, false),
            M(Numbered(UnderName, 3), 4, 96, "Settle just below threshold.", true, 80, 90),
            M(Numbered(OverName, 2), 2, 106, "Lift power, then regain control.", true, 82, 92),
            M(Numbered(UnderName, 4), 4, 98, "Keep breathing deliberate.", true, 80, 90),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Experienced => Workout("threshold-experienced", "Threshold Control", "Long threshold sets with deliberate over-under changes.", TrainingObjective.Threshold, level,
            M(WarmUpName, 12, 55, BuildSmoothly, false),
            M(Numbered(UnderName, 1), 5, 96, SettleBelowThreshold, true, 80, 90),
            M(Numbered(OverName, 1), 2, 106, LiftPowerWithoutRushingCadence, true, 82, 92),
            M(Numbered(UnderName, 2), 5, 98, ReturnToSteadyControl, true, 80, 90),
            M(Numbered(OverName, 2), 2, 108, "Lift power without sprinting.", true, 82, 92),
            M(FloatName, 5, 52, RecoverBeforeSecondSet, false),
            M(Numbered(UnderName, 3), 5, 98, SettleBelowThreshold, true, 80, 90),
            M(Numbered(OverName, 3), 2, 108, LiftPowerWithoutRushingCadence, true, 82, 92),
            M(Numbered(UnderName, 4), 5, 100, ReturnToSteadyControl, true, 80, 90),
            M("Over 4", 2, 110, "Finish strong and controlled.", true, 82, 92),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Advanced => Workout("threshold-advanced", "Threshold Cascade", "Extended over-under work for sustained race pressure.", TrainingObjective.Threshold, level,
            M(WarmUpName, 14, 55, BuildSmoothly, false),
            M(Numbered(UnderName, 1), 6, 98, SettleBelowThreshold, true, 80, 90),
            M(Numbered(OverName, 1), 2, 108, LiftPowerWithoutRushingCadence, true, 82, 92),
            M(Numbered(UnderName, 2), 6, 100, ReturnToSteadyControl, true, 80, 90),
            M(Numbered(OverName, 2), 2, 110, "Hold the surge with composure.", true, 82, 92),
            M(FloatName, 5, 52, RecoverBeforeSecondSet, false),
            M(Numbered(UnderName, 3), 6, 100, SettleBelowThreshold, true, 80, 90),
            M(Numbered(OverName, 3), 2, 110, LiftPowerWithoutRushingCadence, true, 82, 92),
            M(Numbered(UnderName, 4), 6, 102, ReturnToSteadyControl, true, 80, 90),
            M("Over 4", 2, 112, "Finish strong and controlled.", true, 82, 92),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        _ => throw new ArgumentOutOfRangeException(nameof(level)),
    };

    private static TrainingWorkout Vo2Max(TrainingExperienceLevel level) => level switch
    {
        TrainingExperienceLevel.Beginner => Workout("vo2-beginner", "Oxygen Sparks", "Short VO2 efforts with complete recovery.", TrainingObjective.Vo2Max, level,
            M(WarmUpName, 10, 55, BuildSmoothly, false),
            M(Numbered(Vo2EffortName, 1), 2, 108, PushFirmly, true, 88, 98),
            M(FloatName, 3, 50, RecoverBeforeRepeating, false),
            M("VO2 effort 2", 2, 110, "Hold a repeatable hard effort.", true, 88, 98),
            M(FloatName, 3, 50, RecoverBeforeRepeating, false),
            M("VO2 effort 3", 2, 112, FinishControlled, true, 88, 98),
            M(CoolDownName, 7, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Developing => Workout("vo2-developing", "Oxygen Ladders", "Progressive VO2 intervals that build time at high oxygen uptake.", TrainingObjective.Vo2Max, level,
            M(WarmUpName, 11, 55, BuildSmoothly, false),
            M(Numbered(Vo2EffortName, 1), 3, 110, PushFirmly, true, 88, 98),
            M(FloatName, 3, 50, RecoverBeforeRepeating, false),
            M("VO2 effort 2", 3, 112, "Keep pressure high but repeatable.", true, 88, 98),
            M(FloatName, 3, 50, RecoverBeforeRepeating, false),
            M("VO2 effort 3", 3, 114, FinishControlled, true, 88, 98),
            M(CoolDownName, 7, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Intermediate => Workout("vo2-intermediate", "VO2 Micro-Blocks", "Two sets of short VO2 efforts with floating recovery.", TrainingObjective.Vo2Max, level,
            M(WarmUpName, 12, 55, BuildSmoothly, false),
            M(Numbered(Vo2Name, 1), 2, 114, PushFirmly, true, 90, 100),
            M(Numbered(FloatName, 1), 1, 60, KeepPedalingLightly, false),
            M(Numbered(Vo2Name, 2), 2, 114, RepeatSamePressure, true, 90, 100),
            M(Numbered(FloatName, 2), 1, 60, KeepPedalingLightly, false),
            M(Numbered(Vo2Name, 3), 2, 116, FinishFirstSetControlled, true, 90, 100),
            M(SetRecoveryName, 5, 50, RecoverBeforeSecondSet, false),
            M(Numbered(Vo2Name, 4), 2, 116, PushFirmly, true, 90, 100),
            M(Numbered(FloatName, 3), 1, 60, KeepPedalingLightly, false),
            M(Numbered(Vo2Name, 5), 2, 118, RepeatSamePressure, true, 90, 100),
            M(Numbered(FloatName, 4), 1, 60, KeepPedalingLightly, false),
            M(Numbered(Vo2Name, 6), 2, 118, FinishControlled, true, 90, 100),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Experienced => Workout("vo2-experienced", "VO2 On-Offs", "Longer VO2 sets with fast floating recoveries.", TrainingObjective.Vo2Max, level,
            M(WarmUpName, 14, 55, BuildSmoothly, false),
            M(Numbered(Vo2Name, 1), 3, 116, PushFirmly, true, 90, 100),
            M(Numbered(FloatName, 1), 1, 62, KeepPedalsMoving, false),
            M(Numbered(Vo2Name, 2), 3, 116, RepeatSamePressure, true, 90, 100),
            M(Numbered(FloatName, 2), 1, 62, KeepPedalsMoving, false),
            M(Numbered(Vo2Name, 3), 3, 118, FinishFirstSetControlled, true, 90, 100),
            M(SetRecoveryName, 5, 50, RecoverBeforeSecondSet, false),
            M(Numbered(Vo2Name, 4), 3, 118, PushFirmly, true, 90, 100),
            M(Numbered(FloatName, 3), 1, 62, KeepPedalsMoving, false),
            M(Numbered(Vo2Name, 5), 3, 120, RepeatSamePressure, true, 90, 100),
            M(Numbered(FloatName, 4), 1, 62, KeepPedalsMoving, false),
            M(Numbered(Vo2Name, 6), 3, 120, FinishControlled, true, 90, 100),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Advanced => Workout("vo2-advanced", "VO2 Capacity", "Dense VO2 intervals with deliberately incomplete recovery.", TrainingObjective.Vo2Max, level,
            M(WarmUpName, 15, 55, BuildSmoothly, false),
            M(Numbered(Vo2Name, 1), 3, 118, PushFirmly, true, 90, 100),
            M(Numbered(FloatName, 1), 1, 62, KeepPedalsMoving, false),
            M(Numbered(Vo2Name, 2), 3, 120, RepeatSamePressure, true, 90, 100),
            M(Numbered(FloatName, 2), 1, 62, KeepPedalsMoving, false),
            M(Numbered(Vo2Name, 3), 3, 120, FinishFirstSetControlled, true, 90, 100),
            M(SetRecoveryName, 5, 50, RecoverBeforeSecondSet, false),
            M(Numbered(Vo2Name, 4), 3, 120, PushFirmly, true, 90, 100),
            M(Numbered(FloatName, 3), 1, 62, KeepPedalsMoving, false),
            M(Numbered(Vo2Name, 5), 3, 122, RepeatSamePressure, true, 90, 100),
            M(Numbered(FloatName, 4), 1, 62, KeepPedalsMoving, false),
            M(Numbered(Vo2Name, 6), 3, 122, FinishControlled, true, 90, 100),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        _ => throw new ArgumentOutOfRangeException(nameof(level)),
    };

    private static TrainingWorkout CadenceSkills(TrainingExperienceLevel level) => level switch
    {
        TrainingExperienceLevel.Beginner => Workout("cadence-beginner", "Smooth Pedals", "Gentle cadence drills for efficient pedaling.", TrainingObjective.CadenceSkills, level,
            M(WarmUpName, 6, 50, BuildSmoothly, false),
            M(Numbered(SpinUpName, 1), 2, 58, "Increase cadence without adding force.", true, 95, 105),
            M(EasyRollName, 3, 50, ReturnToRelaxedRhythm, false),
            M(Numbered(SpinUpName, 2), 2, 60, "Keep hips stable.", true, 98, 108),
            M(EasyRollName, 3, 50, ReturnToRelaxedRhythm, false),
            M(Numbered(TorqueName, 1), 3, 66, "Use a controlled, heavier gear.", true, 65, 75),
            M(EasyRollName, 3, 50, LightenGear, false),
            M("Spin-up 3", 2, 62, "Stay smooth and quiet.", true, 100, 110),
            M(CoolDownName, 5, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Developing => Workout("cadence-developing", "Cadence Control", "Alternating spin-ups and low-cadence strength work.", TrainingObjective.CadenceSkills, level,
            M(WarmUpName, 8, 50, BuildSmoothly, false),
            M(Numbered(SpinUpName, 1), 3, 60, "Increase cadence without bouncing.", true, 98, 108),
            M(EasyRollName, 2, 50, ReturnToRelaxedRhythm, false),
            M(Numbered(TorqueName, 1), 4, 70, PressSmoothly, true, 65, 75),
            M(EasyRollName, 3, 50, LightenGear, false),
            M(Numbered(SpinUpName, 2), 3, 62, "Keep hips stable.", true, 100, 110),
            M(EasyRollName, 2, 50, ReturnToRelaxedRhythm, false),
            M(Numbered(TorqueName, 2), 4, 72, "Stay seated and controlled.", true, 65, 75),
            M(CoolDownName, 6, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Intermediate => Workout("cadence-intermediate", "Torque and Spin", "Cadence range work that links low-cadence force and fast legs.", TrainingObjective.CadenceSkills, level,
            M(WarmUpName, 10, 50, BuildSmoothly, false),
            M(Numbered(TorqueName, 1), 5, 75, PressSmoothly, true, 60, 70),
            M(Numbered(SpinUpName, 1), 2, 62, ShiftLighterAndSpinFreely, true, 102, 112),
            M(EasyRollName, 3, 50, ReturnToRelaxedRhythm, false),
            M(Numbered(TorqueName, 2), 5, 78, "Keep the upper body still.", true, 60, 70),
            M(Numbered(SpinUpName, 2), 2, 64, ShiftLighterAndSpinFreely, true, 104, 114),
            M(EasyRollName, 3, 50, ReturnToRelaxedRhythm, false),
            M(CadenceCloseName, 5, 70, "Choose the most efficient rhythm.", true, 88, 98),
            M(CoolDownName, 7, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Experienced => Workout("cadence-experienced", "Cadence Range", "Longer torque and spin pairs for pedaling economy.", TrainingObjective.CadenceSkills, level,
            M(WarmUpName, 12, 50, BuildSmoothly, false),
            M(Numbered(TorqueName, 1), 6, 78, PressSmoothly, true, 60, 70),
            M(Numbered(SpinUpName, 1), 3, 65, ShiftLighterAndSpinFreely, true, 104, 114),
            M(EasyRollName, 3, 50, ReturnToRelaxedRhythm, false),
            M(Numbered(TorqueName, 2), 6, 80, "Keep the upper body still.", true, 60, 70),
            M(Numbered(SpinUpName, 2), 3, 67, ShiftLighterAndSpinFreely, true, 106, 116),
            M(EasyRollName, 3, 50, ReturnToRelaxedRhythm, false),
            M("Torque 3", 5, 82, "Hold pressure without grinding.", true, 62, 72),
            M(CadenceCloseName, 5, 72, "Choose the most efficient rhythm.", true, 90, 100),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Advanced => Workout("cadence-advanced", "Pedaling Economy", "Extended cadence contrast work for efficient force production.", TrainingObjective.CadenceSkills, level,
            M(WarmUpName, 12, 50, BuildSmoothly, false),
            M(Numbered(TorqueName, 1), 7, 80, PressSmoothly, true, 60, 70),
            M(Numbered(SpinUpName, 1), 3, 67, ShiftLighterAndSpinFreely, true, 106, 116),
            M(EasyRollName, 3, 50, ReturnToRelaxedRhythm, false),
            M(Numbered(TorqueName, 2), 7, 82, "Keep the upper body still.", true, 60, 70),
            M(Numbered(SpinUpName, 2), 3, 69, ShiftLighterAndSpinFreely, true, 108, 118),
            M(EasyRollName, 3, 50, ReturnToRelaxedRhythm, false),
            M("Torque 3", 6, 84, "Hold pressure without grinding.", true, 62, 72),
            M(CadenceCloseName, 6, 75, "Choose the most efficient rhythm.", true, 90, 100),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        _ => throw new ArgumentOutOfRangeException(nameof(level)),
    };

    private static TrainingWorkout Anaerobic(TrainingExperienceLevel level) => level switch
    {
        TrainingExperienceLevel.Beginner => Workout("anaerobic-beginner", "Burst Primer", "Short hard bursts with complete recovery.", TrainingObjective.Anaerobic, level,
            M(WarmUpName, 10, 55, BuildSmoothly, false),
            S(Numbered(BurstName, 1), 30, 122, "Accelerate hard but stay seated.", true, 90, 105),
            M("Full recovery", 3, 48, "Recover completely.", false),
            S(Numbered(BurstName, 2), 30, 124, "Accelerate hard but stay seated.", true, 90, 105),
            M("Full recovery", 3, 48, "Recover completely.", false),
            S(Numbered(BurstName, 3), 30, 126, FinishSharp, true, 90, 105),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Developing => Workout("anaerobic-developing", "30-30 Starter", "Two sets of short anaerobic bursts with full set recovery.", TrainingObjective.Anaerobic, level,
            M(WarmUpName, 11, 55, BuildSmoothly, false),
            S(Numbered(BurstName, 1), 30, 126, AccelerateSharply, true, 92, 108),
            S(Numbered(FloatName, 1), 30, 55, KeepPedalsMoving, false),
            S(Numbered(BurstName, 2), 30, 126, RepeatSameAcceleration, true, 92, 108),
            S(Numbered(FloatName, 2), 30, 55, KeepPedalsMoving, false),
            S(Numbered(BurstName, 3), 30, 128, FinishFirstSetControlled, true, 92, 108),
            M(SetRecoveryName, 4, 48, RecoverCompletelyBeforeSecondSet, false),
            S(Numbered(BurstName, 4), 30, 128, AccelerateSharply, true, 92, 108),
            S(Numbered(FloatName, 3), 30, 55, KeepPedalsMoving, false),
            S(Numbered(BurstName, 5), 30, 130, RepeatSameAcceleration, true, 92, 108),
            S(Numbered(FloatName, 4), 30, 55, KeepPedalsMoving, false),
            S(Numbered(BurstName, 6), 30, 130, FinishSharp, true, 92, 108),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Intermediate => Workout("anaerobic-intermediate", "Anaerobic Repeatability", "Dense 40-second efforts that rehearse repeatable power.", TrainingObjective.Anaerobic, level,
            M(WarmUpName, 12, 55, BuildSmoothly, false),
            S(Numbered(BurstName, 1), 40, 130, AccelerateSharply, true, 94, 110),
            S(Numbered(FloatName, 1), 50, 55, KeepMovingNoCoast, false),
            S(Numbered(BurstName, 2), 40, 130, RepeatSameAcceleration, true, 94, 110),
            S(Numbered(FloatName, 2), 50, 55, KeepMovingNoCoast, false),
            S(Numbered(BurstName, 3), 40, 132, FinishFirstSetControlled, true, 94, 110),
            M(SetRecoveryName, 5, 48, RecoverCompletelyBeforeSecondSet, false),
            S(Numbered(BurstName, 4), 40, 132, AccelerateSharply, true, 94, 110),
            S(Numbered(FloatName, 3), 50, 55, KeepMovingNoCoast, false),
            S(Numbered(BurstName, 5), 40, 134, RepeatSameAcceleration, true, 94, 110),
            S(Numbered(FloatName, 4), 50, 55, KeepMovingNoCoast, false),
            S(Numbered(BurstName, 6), 40, 134, FinishSharp, true, 94, 110),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Experienced => Workout("anaerobic-experienced", "Punchy Repeatability", "Two demanding sets of anaerobic efforts with incomplete floats.", TrainingObjective.Anaerobic, level,
            M(WarmUpName, 14, 55, BuildSmoothly, false),
            S(Numbered(BurstName, 1), 45, 134, AccelerateSharply, true, 94, 110),
            S(Numbered(FloatName, 1), 45, 58, KeepMovingNoCoast, false),
            S(Numbered(BurstName, 2), 45, 134, RepeatSameAcceleration, true, 94, 110),
            S(Numbered(FloatName, 2), 45, 58, KeepMovingNoCoast, false),
            S(Numbered(BurstName, 3), 45, 136, FinishFirstSetControlled, true, 94, 110),
            M(SetRecoveryName, 5, 48, RecoverCompletelyBeforeSecondSet, false),
            S(Numbered(BurstName, 4), 45, 136, AccelerateSharply, true, 94, 110),
            S(Numbered(FloatName, 3), 45, 58, KeepMovingNoCoast, false),
            S(Numbered(BurstName, 5), 45, 138, RepeatSameAcceleration, true, 94, 110),
            S(Numbered(FloatName, 4), 45, 58, KeepMovingNoCoast, false),
            S(Numbered(BurstName, 6), 45, 138, FinishSharp, true, 94, 110),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        TrainingExperienceLevel.Advanced => Workout("anaerobic-advanced", "Anaerobic Capacity", "Long repeated anaerobic efforts that reward controlled starts.", TrainingObjective.Anaerobic, level,
            M(WarmUpName, 15, 55, BuildSmoothly, false),
            M(Numbered(BurstName, 1), 1, 138, "Accelerate hard, then hold form.", true, 94, 110),
            M(Numbered(FloatName, 1), 1, 60, KeepMovingNoCoast, false),
            M(Numbered(BurstName, 2), 1, 138, RepeatSameAcceleration, true, 94, 110),
            M(Numbered(FloatName, 2), 1, 60, KeepMovingNoCoast, false),
            M(Numbered(BurstName, 3), 1, 140, FinishFirstSetControlled, true, 94, 110),
            M(SetRecoveryName, 5, 48, RecoverCompletelyBeforeSecondSet, false),
            M(Numbered(BurstName, 4), 1, 140, "Accelerate hard, then hold form.", true, 94, 110),
            M(Numbered(FloatName, 3), 1, 60, KeepMovingNoCoast, false),
            M(Numbered(BurstName, 5), 1, 142, RepeatSameAcceleration, true, 94, 110),
            M(Numbered(FloatName, 4), 1, 60, KeepMovingNoCoast, false),
            M(Numbered(BurstName, 6), 1, 142, FinishSharp, true, 94, 110),
            M(CoolDownName, 8, 45, EaseOffGradually, false)),
        _ => throw new ArgumentOutOfRangeException(nameof(level)),
    };

    private static TrainingWorkout Workout(
        string id,
        string name,
        string description,
        TrainingObjective objective,
        TrainingExperienceLevel level,
        params TrainingSegment[] segments) => new(id, name, description, objective, level, segments);

    private static string Numbered(string name, int number) => $"{name} {number}";

    private static TrainingSegment M(
        string name,
        int minutes,
        double target,
        string cue,
        bool countsTowardAdherence,
        int? minimumCadenceRpm = null,
        int? maximumCadenceRpm = null) => new(name, TimeSpan.FromMinutes(minutes), target, minimumCadenceRpm, maximumCadenceRpm, cue, countsTowardAdherence);

    private static TrainingSegment S(
        string name,
        int seconds,
        double target,
        string cue,
        bool countsTowardAdherence,
        int? minimumCadenceRpm = null,
        int? maximumCadenceRpm = null) => new(name, TimeSpan.FromSeconds(seconds), target, minimumCadenceRpm, maximumCadenceRpm, cue, countsTowardAdherence);
}