<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Stationary.Ftms/Stationary.Ftms.csproj" />
    <PackageReference Include="TUnit" />
  </ItemGroup>
</Project>