using System.Buffers.Binary;

namespace Stationary.Ftms;

public readonly record struct CrossTrainerData(
    bool MoreData, bool IsMovingBackward, ushort? InstantaneousSpeed, ushort? AverageSpeed, uint? TotalDistance,
    ushort? StepPerMinute, ushort? AverageStepRate, ushort? StrideCount, ushort? PositiveElevationGain,
    ushort? NegativeElevationGain, short? Inclination, short? RampAngleSetting, sbyte? ResistanceLevel,
    short? InstantaneousPower, short? AveragePower, ushort? TotalEnergy, ushort? EnergyPerHour, byte? EnergyPerMinute,
    byte? HeartRate, byte? MetabolicEquivalent, ushort? ElapsedTime, ushort? RemainingTime)
{
    public double? InstantaneousSpeedKilometersPerHour => InstantaneousSpeed is ushort value ? value / 100d : null;
    public double? MetabolicEquivalentValue => MetabolicEquivalent is byte value ? value / 10d : null;
    public int GetEncodedLength() => 2 + (!MoreData ? 2 : 0) + (AverageSpeed.HasValue ? 2 : 0) + (TotalDistance.HasValue ? 3 : 0) + (HasStepRates ? 4 : 0) + (StrideCount.HasValue ? 2 : 0) + (HasElevationGain ? 4 : 0) + (HasInclination ? 4 : 0) + (ResistanceLevel.HasValue ? 1 : 0) + (InstantaneousPower.HasValue ? 2 : 0) + (AveragePower.HasValue ? 2 : 0) + (HasEnergy ? 5 : 0) + (HeartRate.HasValue ? 1 : 0) + (MetabolicEquivalent.HasValue ? 1 : 0) + (ElapsedTime.HasValue ? 2 : 0) + (RemainingTime.HasValue ? 2 : 0);
    public static FtmsDecodeStatus TryDecode(ReadOnlySpan<byte> source, out CrossTrainerData value, FtmsValidationMode validationMode = FtmsValidationMode.Compatible)
    {
        value = default; if (source.Length < 2) return FtmsDecodeStatus.InsufficientData; var flags = BinaryPrimitives.ReadUInt16LittleEndian(source); var reader = new FtmsFieldReader(source[2..]); var moreData = (flags & 1) != 0; ushort? speed = null, averageSpeed = null, stepPerMinute = null, averageStepRate = null, strideCount = null, positiveElevationGain = null, negativeElevationGain = null, totalEnergy = null, energyPerHour = null, elapsedTime = null, remainingTime = null; uint? totalDistance = null; short? inclination = null, rampAngle = null, instantaneousPower = null, averagePower = null; sbyte? resistance = null; byte? energyPerMinute = null, heartRate = null, metabolicEquivalent = null;
        if (!moreData) { if (!reader.TryReadUInt16(out var raw)) return FtmsDecodeStatus.InsufficientData; speed = raw; }
        if (!StepClimberData.ReadOptional((flags & 2) != 0, ref reader, out averageSpeed) || !StepClimberData.ReadOptionalUInt24((flags & 4) != 0, ref reader, out totalDistance) || !ReadUInt16Pair((flags & 8) != 0, ref reader, out stepPerMinute, out averageStepRate) || !StepClimberData.ReadOptional((flags & 16) != 0, ref reader, out strideCount) || !ReadUInt16Pair((flags & 32) != 0, ref reader, out positiveElevationGain, out negativeElevationGain) || !ReadInt16Pair((flags & 64) != 0, ref reader, out inclination, out rampAngle) || !ReadSByte((flags & 128) != 0, ref reader, out resistance) || !StepClimberData.ReadOptional((flags & 256) != 0, ref reader, out instantaneousPower) || !StepClimberData.ReadOptional((flags & 512) != 0, ref reader, out averagePower) || !StepClimberData.ReadEnergy((flags & 1024) != 0, ref reader, out totalEnergy, out energyPerHour, out energyPerMinute) || !StepClimberData.ReadOptional((flags & 2048) != 0, ref reader, out heartRate) || !StepClimberData.ReadOptional((flags & 4096) != 0, ref reader, out metabolicEquivalent) || !StepClimberData.ReadOptional((flags & 8192) != 0, ref reader, out elapsedTime) || !StepClimberData.ReadOptional((flags & 16384) != 0, ref reader, out remainingTime)) return FtmsDecodeStatus.InsufficientData;
        if (validationMode == FtmsValidationMode.Strict && reader.Consumed != source.Length - 2) return FtmsDecodeStatus.TrailingData; value = new(moreData, (flags & 0x8000) != 0, speed, averageSpeed, totalDistance, stepPerMinute, averageStepRate, strideCount, positiveElevationGain, negativeElevationGain, inclination, rampAngle, resistance, instantaneousPower, averagePower, totalEnergy, energyPerHour, energyPerMinute, heartRate, metabolicEquivalent, elapsedTime, remainingTime); return FtmsDecodeStatus.Success;
    }
    public bool TryEncode(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0; if ((!MoreData && !InstantaneousSpeed.HasValue) || destination.Length < GetEncodedLength()) return false; var writer = new FtmsFieldWriter(destination); writer.WriteUInt16(GetFlags()); if (!MoreData) writer.WriteUInt16(InstantaneousSpeed!.Value); if (AverageSpeed is ushort a) writer.WriteUInt16(a); if (TotalDistance is uint b) writer.WriteUInt24(b); WriteUInt16Pair(ref writer, HasStepRates, StepPerMinute, AverageStepRate); if (StrideCount is ushort c) writer.WriteUInt16(c); WriteUInt16Pair(ref writer, HasElevationGain, PositiveElevationGain, NegativeElevationGain); WriteInt16Pair(ref writer, HasInclination, Inclination, RampAngleSetting); if (ResistanceLevel is sbyte d) writer.WriteByte((byte)d); if (InstantaneousPower is short e) writer.WriteInt16(e); if (AveragePower is short f) writer.WriteInt16(f); StepClimberData.WriteEnergy(ref writer, HasEnergy, TotalEnergy, EnergyPerHour, EnergyPerMinute); if (HeartRate is byte g) writer.WriteByte(g); if (MetabolicEquivalent is byte h) writer.WriteByte(h); if (ElapsedTime is ushort i) writer.WriteUInt16(i); if (RemainingTime is ushort j) writer.WriteUInt16(j); bytesWritten = writer.Written; return true;
    }
    private bool HasStepRates => StepPerMinute.HasValue || AverageStepRate.HasValue; private bool HasElevationGain => PositiveElevationGain.HasValue || NegativeElevationGain.HasValue; private bool HasInclination => Inclination.HasValue || RampAngleSetting.HasValue; private bool HasEnergy => TotalEnergy.HasValue || EnergyPerHour.HasValue || EnergyPerMinute.HasValue;
    private ushort GetFlags() => (ushort)((MoreData ? 1 : 0) | (AverageSpeed.HasValue ? 2 : 0) | (TotalDistance.HasValue ? 4 : 0) | (HasStepRates ? 8 : 0) | (StrideCount.HasValue ? 16 : 0) | (HasElevationGain ? 32 : 0) | (HasInclination ? 64 : 0) | (ResistanceLevel.HasValue ? 128 : 0) | (InstantaneousPower.HasValue ? 256 : 0) | (AveragePower.HasValue ? 512 : 0) | (HasEnergy ? 1024 : 0) | (HeartRate.HasValue ? 2048 : 0) | (MetabolicEquivalent.HasValue ? 4096 : 0) | (ElapsedTime.HasValue ? 8192 : 0) | (RemainingTime.HasValue ? 16384 : 0) | (IsMovingBackward ? 32768 : 0));
    private static bool ReadSByte(bool present, ref FtmsFieldReader reader, out sbyte? value) { value = null; if (!present) return true; if (!reader.TryReadByte(out var raw)) return false; value = unchecked((sbyte)raw); return true; }
    private static bool ReadInt16Pair(bool present, ref FtmsFieldReader reader, out short? first, out short? second) { first = null; second = null; if (!present) return true; if (!reader.TryReadInt16(out var a) || !reader.TryReadInt16(out var b)) return false; first = a; second = b; return true; }
    private static bool ReadUInt16Pair(bool present, ref FtmsFieldReader reader, out ushort? first, out ushort? second) { first = null; second = null; if (!present) return true; if (!reader.TryReadUInt16(out var a) || !reader.TryReadUInt16(out var b)) return false; first = a; second = b; return true; }
    private static void WriteInt16Pair(ref FtmsFieldWriter writer, bool present, short? first, short? second) { if (!present) return; writer.WriteInt16(first ?? short.MaxValue); writer.WriteInt16(second ?? short.MaxValue); }
    private static void WriteUInt16Pair(ref FtmsFieldWriter writer, bool present, ushort? first, ushort? second) { if (!present) return; writer.WriteUInt16(first ?? ushort.MaxValue); writer.WriteUInt16(second ?? ushort.MaxValue); }
}