using System.Buffers.Binary;

namespace Stationary.Ftms;

public readonly record struct TreadmillData(
    bool MoreData, ushort? InstantaneousSpeed, ushort? AverageSpeed, uint? TotalDistance, short? Inclination,
    short? RampAngleSetting, ushort? PositiveElevationGain, ushort? NegativeElevationGain, ushort? InstantaneousPace,
    ushort? AveragePace, ushort? TotalEnergy, ushort? EnergyPerHour, byte? EnergyPerMinute, byte? HeartRate,
    byte? MetabolicEquivalent, ushort? ElapsedTime, ushort? RemainingTime, short? ForceOnBelt, short? PowerOutput)
{
    private const ushort DefinedFlagsMask = 0x1FFF;
    public double? InstantaneousSpeedKilometersPerHour => InstantaneousSpeed is ushort value ? value / 100d : null;
    public double? MetabolicEquivalentValue => MetabolicEquivalent is byte value ? value / 10d : null;
    public int GetEncodedLength() => 2 + (!MoreData ? 2 : 0) + (AverageSpeed.HasValue ? 2 : 0) + (TotalDistance.HasValue ? 3 : 0) + (HasInclination ? 4 : 0) + (HasElevationGain ? 4 : 0) + (InstantaneousPace.HasValue ? 2 : 0) + (AveragePace.HasValue ? 2 : 0) + (HasEnergy ? 5 : 0) + (HeartRate.HasValue ? 1 : 0) + (MetabolicEquivalent.HasValue ? 1 : 0) + (ElapsedTime.HasValue ? 2 : 0) + (RemainingTime.HasValue ? 2 : 0) + (HasForceAndPower ? 4 : 0);
    public static FtmsDecodeStatus TryDecode(ReadOnlySpan<byte> source, out TreadmillData value, FtmsValidationMode validationMode = FtmsValidationMode.Compatible)
    {
        value = default; if (source.Length < 2) return FtmsDecodeStatus.InsufficientData; var flags = BinaryPrimitives.ReadUInt16LittleEndian(source); if (validationMode == FtmsValidationMode.Strict && (flags & ~DefinedFlagsMask) != 0) return FtmsDecodeStatus.InvalidFlags;
        var reader = new FtmsFieldReader(source[2..]); var moreData = (flags & 1) != 0; ushort? speed = null, averageSpeed = null, positiveElevationGain = null, negativeElevationGain = null, instantaneousPace = null, averagePace = null, totalEnergy = null, energyPerHour = null, elapsedTime = null, remainingTime = null; uint? totalDistance = null; short? inclination = null, rampAngle = null, force = null, power = null; byte? energyPerMinute = null, heartRate = null, metabolicEquivalent = null;
        if (!moreData) { if (!reader.TryReadUInt16(out var raw)) return FtmsDecodeStatus.InsufficientData; speed = raw; }
        if (!StepClimberData.ReadOptional((flags & 2) != 0, ref reader, out averageSpeed) || !StepClimberData.ReadOptionalUInt24((flags & 4) != 0, ref reader, out totalDistance) || !ReadPair((flags & 8) != 0, ref reader, out inclination, out rampAngle) || !ReadPair((flags & 16) != 0, ref reader, out positiveElevationGain, out negativeElevationGain) || !StepClimberData.ReadOptional((flags & 32) != 0, ref reader, out instantaneousPace) || !StepClimberData.ReadOptional((flags & 64) != 0, ref reader, out averagePace) || !StepClimberData.ReadEnergy((flags & 128) != 0, ref reader, out totalEnergy, out energyPerHour, out energyPerMinute) || !StepClimberData.ReadOptional((flags & 256) != 0, ref reader, out heartRate) || !StepClimberData.ReadOptional((flags & 512) != 0, ref reader, out metabolicEquivalent) || !StepClimberData.ReadOptional((flags & 1024) != 0, ref reader, out elapsedTime) || !StepClimberData.ReadOptional((flags & 2048) != 0, ref reader, out remainingTime) || !ReadPair((flags & 4096) != 0, ref reader, out force, out power)) return FtmsDecodeStatus.InsufficientData;
        if (validationMode == FtmsValidationMode.Strict && reader.Consumed != source.Length - 2) return FtmsDecodeStatus.TrailingData; value = new(moreData, speed, averageSpeed, totalDistance, inclination, rampAngle, positiveElevationGain, negativeElevationGain, instantaneousPace, averagePace, totalEnergy, energyPerHour, energyPerMinute, heartRate, metabolicEquivalent, elapsedTime, remainingTime, force, power); return FtmsDecodeStatus.Success;
    }
    public bool TryEncode(Span<byte> destination, out int bytesWritten)
    {
        bytesWritten = 0; if ((!MoreData && !InstantaneousSpeed.HasValue) || destination.Length < GetEncodedLength()) return false; var writer = new FtmsFieldWriter(destination); writer.WriteUInt16(GetFlags()); if (!MoreData) writer.WriteUInt16(InstantaneousSpeed!.Value); if (AverageSpeed is ushort a) writer.WriteUInt16(a); if (TotalDistance is uint b) writer.WriteUInt24(b); WritePair(ref writer, HasInclination, Inclination, RampAngleSetting); WritePair(ref writer, HasElevationGain, PositiveElevationGain, NegativeElevationGain); if (InstantaneousPace is ushort c) writer.WriteUInt16(c); if (AveragePace is ushort d) writer.WriteUInt16(d); StepClimberData.WriteEnergy(ref writer, HasEnergy, TotalEnergy, EnergyPerHour, EnergyPerMinute); if (HeartRate is byte e) writer.WriteByte(e); if (MetabolicEquivalent is byte f) writer.WriteByte(f); if (ElapsedTime is ushort g) writer.WriteUInt16(g); if (RemainingTime is ushort h) writer.WriteUInt16(h); WritePair(ref writer, HasForceAndPower, ForceOnBelt, PowerOutput); bytesWritten = writer.Written; return true;
    }
    private bool HasInclination => Inclination.HasValue || RampAngleSetting.HasValue; private bool HasElevationGain => PositiveElevationGain.HasValue || NegativeElevationGain.HasValue; private bool HasEnergy => TotalEnergy.HasValue || EnergyPerHour.HasValue || EnergyPerMinute.HasValue; private bool HasForceAndPower => ForceOnBelt.HasValue || PowerOutput.HasValue;
    private ushort GetFlags() => (ushort)((MoreData ? 1 : 0) | (AverageSpeed.HasValue ? 2 : 0) | (TotalDistance.HasValue ? 4 : 0) | (HasInclination ? 8 : 0) | (HasElevationGain ? 16 : 0) | (InstantaneousPace.HasValue ? 32 : 0) | (AveragePace.HasValue ? 64 : 0) | (HasEnergy ? 128 : 0) | (HeartRate.HasValue ? 256 : 0) | (MetabolicEquivalent.HasValue ? 512 : 0) | (ElapsedTime.HasValue ? 1024 : 0) | (RemainingTime.HasValue ? 2048 : 0) | (HasForceAndPower ? 4096 : 0));
    private static bool ReadPair(bool present, ref FtmsFieldReader reader, out short? first, out short? second) { first = null; second = null; if (!present) return true; if (!reader.TryReadInt16(out var a) || !reader.TryReadInt16(out var b)) return false; first = a; second = b; return true; }
    private static bool ReadPair(bool present, ref FtmsFieldReader reader, out ushort? first, out ushort? second) { first = null; second = null; if (!present) return true; if (!reader.TryReadUInt16(out var a) || !reader.TryReadUInt16(out var b)) return false; first = a; second = b; return true; }
    private static void WritePair(ref FtmsFieldWriter writer, bool present, short? first, short? second) { if (!present) return; writer.WriteInt16(first ?? short.MaxValue); writer.WriteInt16(second ?? short.MaxValue); }
    private static void WritePair(ref FtmsFieldWriter writer, bool present, ushort? first, ushort? second) { if (!present) return; writer.WriteUInt16(first ?? ushort.MaxValue); writer.WriteUInt16(second ?? ushort.MaxValue); }
}